---
title: "Takım: Code Busters"
sidebar: false 
---

MUY665-İş Analitiği dersi takım sayfamıza hoş geldiniz.

Bu analitik çalışmalarımızı paylaşıyoruz.

Lütfen faaliyetlerimizi görmek için için bizi takipte kalın.



## Takım Üyeleri

1.  [Aysu Gökkaya](/takim/aysugökkaya.qmd)

2.  [Azra Bozkurt](/takim/azrabozkurt.qmd)

3.  [Samet Burak Çayır](/takim/burakçayır.qmd)

4.  [Anıl Metin](/takim/anilmetin.qmd)

5.  [Dilek Beyter](/takim/dilekbeyter.qmd)

6.  [Elif Selin Buğdayıcı](/takim/elifselinbuğdayıcı.qmd)


## Proje Adı
MUY665-Henüz belirsiz

## Proje Konusu
Örnek:
Bu projede MUY665-İş Analitiği ders içeriğinin analitik yaklaşımlarla iyileştirilmesini hedefledik. Bu doğrultuda tüm üniversitelerdeki benzer derslerin verisini toplayarak bir veri seti oluşturduk Analiz için ........ yöntemleri kullanarak, ....... çalışmaları yaptık Sonuç olarak, MUY660-İş Analitiği dersinin dünyadaki tüm derslerden daha iyi olduğunu ve bu dersi aldığımız için çok mutlu olduğumuzu tespit ettik.


## Veri Seti Hakkında Özet Bilgi


## Sonuçlar
Burada key takeways verilmelidir. En az 3 en fazla 5 madde ile çarpıcı sonuçlar sunulmalıdır.